### ISSUE TITLE
Group vs individual searches

### ISSUE THREAD

**Issue by gregmaxin** [uwblueprint/KidsAbility#108]
Current searches find the available time between all the searched clinicians. This task requires minor edits to the search page and medium edits to the algorithm on the display pages

What if you searched for 3 different clinicians but wanted to know when all 3 were individually available?

i.e

Group: P1,P2,P3 8:30-11:00

Individual: 
P1: 8:30-11:00
P2: 8:00-11:30
P3: 8:00-4:30pm

---
*Potential Solution*
Give users the option to check/uncheck clinicians they searched for on the results page. Could implement this solely on the front-end by hiding times that include the unchecked clinicians.

![image.png](https://images.zenhubusercontent.com/5ce735b053933838cf068ea5/5e43da27-37dd-4ffe-97eb-4c2858126b39)

**Comment by kevinkwchan** [comment]
Design thoughts:
- Google calendar "Find a time" feature for inspiration
- algorithm is currently designed to only show available times, not booked times

**Comment by Kemanning** [comment]
- Tiered availability... display “all”, “2/3”, “1/3” etc in different colours in the calendar... (only highest, highest -1, highest -2...)
- can we modify the current calendar component?
