### ISSUE TITLE
Add days of the week options

### ISSUE THREAD

**Issue by gregmaxin** [uwblueprint/KidsAbility#109]
Add another drop-down menu that allows you to pick by days of the week.

This requires changes to the UI and potentially CSS

![image.png](https://images.zenhubusercontent.com/5ce735b053933838cf068ea5/4c106979-0372-4fb1-ac2c-ee4592a231be)

Add new drop down and rearrange the options slightly

**Comment by kevinkwchan** [comment]
![image.png](https://images.zenhubusercontent.com/5ce735b053933838cf068ea5/6a5b5017-fe4e-40a1-b257-e6966fde2e67)

Add another drop-down
"Preferred days of the week?"
Do we still need time of day??

**Comment by matthewfollegot** [comment]
Since this affects the UI, I'm also going to be updating the UI based on Kevin's latest iteration.
