### ISSUE TITLE
The [Required] clinician search param can be left blank

### ISSUE THREAD

**Issue by gregmaxin** [uwblueprint/KidsAbility#118]
Don't allow a search if there is no clinicians selected

Created pull request for this :D 

https://github.com/uwblueprint/KidsAbility/pull/148

**Comment by kevinkwchan** [comment]
IT breaks everything. 

Even if done correctly, can still get an empty search. Consider an empty state design "No results found" to be more explicit that it is not broken.

**Comment by Kemanning** [comment]
Interestingly: in my iPad it just doesn’t let me search unless a clinician is inputted, it doesn’t straight up break
