### ISSUE TITLE
[TASK] - All Location Information

### ISSUE THREAD

**Issue by gregmaxin** [uwblueprint/KidsAbility#4]
To Do:
- Take the information in the pdf [(](https://drive.google.com/open?id=19LI4CXPEL04OkEHH--CGAmRTHqPoAUTO) and put it into locations.js in a folder called "constants"

**Comment by gregmaxin** [comment]
https://drive.google.com/open?id=19LI4CXPEL04OkEHH--CGAmRTHqPoAUTO

Locations with the item status of "I" are 'inactive', I don't think we need to include them

**Comment by hannahwang12** [comment]
I've finished adding all the locations from the first page of the pdf into the locations.js file on this branch: https://github.com/uwblueprint/KidsAbility/tree/location-data

**Comment by gregmaxin** [comment]
Thanks @hannahwang12
