### ISSUE TITLE
[TASK] - Add your name to the readme (Karissa)

### ISSUE THREAD

**Issue by gregmaxin** [uwblueprint/KidsAbility#7]

**Comment by Kemanning** [comment]
I have completed editing the Readme in an app I downloaded earlier today, I am having trouble pushing my branch (I get an error on the app) will show you in person, @GodGreg 
#7
![5f2fa1e2-28b1-44ca-b195-d9548ac9167c](https://user-images.githubusercontent.com/46057450/51446030-3c340080-1cda-11e9-8880-0bf692d75df8.png)
![7263b711-802b-4cc7-86c0-021fe66b022c](https://user-images.githubusercontent.com/46057450/51446031-3c340080-1cda-11e9-8997-672ed23df0fa.png)
